image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: 'Deployment to Staging'
          deployment: Production
          script:
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                  SSH_USER: 'homeqdba'
                  SERVER: '137.184.216.221'
                  MODE: 'script'
                  PORT: '22'
                  COMMAND: 'cd /var/www/hd && ./deploy-production.sh'