image: atlassian/default-image:2

pipelines:
  branches:
    development:
      - step:
          name: 'Deployment to Staging'
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                SSH_USER: 'homeqdba'
                SERVER: '162.0.229.211'
                MODE: 'script' # Optional
                PORT: '21098' # Optional
                COMMAND: 'deploy-staging.sh'
    master:
      - step:
          name: 'Clone Repository and SonarCloud Scan'
          script:
            - pipe: sonarsource/sonarcloud-scan:2.0.0
              variables:
                SONAR_TOKEN: ${SONAR_TOKEN}
                SONAR_SCANNER_OPTS: "-X -Dsonar.verbose=true"
                SONAR_PROJECT_KEY: "ikonicsolution_hd-v2"
                SONAR_ORGANIZATION: "herco"
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
              variables:
                SONAR_TOKEN: ${SONAR_TOKEN}  # Required to check the quality gate status
      - step:
          name: 'Deployment to Production'
          deployment: production
          script:
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                SSH_USER: 'homeqdba'
                SERVER: '164.90.255.76'
                MODE: 'script' # Optional
                COMMAND: 'deploy-production.sh'

clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache
