image: atlassian/default-image:2

pipelines:
  branches:
    development:
      - step:
          name: 'Deployment to Staging'
          deployment: master
          script:
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                  SSH_USER: 'homeqdba'
                  SERVER: '162.0.229.211'
                  MODE: 'script'
                  PORT: '21098'
                  COMMAND: 'deploy-staging.sh'