image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: 'Test SSH Connection'
          script:
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                SSH_USER: 'homeqdba'
                SERVER: '164.90.255.76'
                MODE: 'command'
                PORT: '22'
                COMMAND: 'echo "SSH connection successful"'
      
      - step:
          name: 'Run Deployment Script'
          script:
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                SSH_USER: 'homeqdba'
                SERVER: '164.90.255.76'
                MODE: 'script'
                PORT: '22'
                COMMAND: 'cd /var/www/hd && bash deploy-production.sh'