# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  branches:
    development:
      - step:
          name: 'Deployment to Staging'
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                  SSH_USER: 'homeqdba'
                  SERVER: '162.0.229.211'
                  MODE: 'script' # Optional
                  PORT: '21098' # Optional
                  COMMAND: 'deploy-staging.sh'
    master:
      - step:
          name: 'SonarCloud Scan'
          caches:
            - sonar
          script:
            - pipe: sonarsource/sonarcloud-scan:2.0.0
              variables:
                SONAR_TOKEN: ${SONAR_TOKEN}
                SONAR_SCANNER_OPTS: "-X -Dsonar.verbose=true"
                SONAR_PROJECT_KEY: "ikonicsolution_hd-v2" 
                SONAR_ORGANIZATION: "herco" 
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
      - step:
          name: 'Deployment to Production'
          deployment: production
          script:
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                  SSH_USER: 'homeqdba'
                  SERVER: '164.90.255.76'
                  MODE: 'script'
                  COMMAND: 'deploy-production.sh'

definitions:
  caches:
    sonar: ~/.sonar/cache

clone:
  depth: full 

