<?php 

return [
    'correios' => [
        'sub_classess' => [
            33162 => 'Packet Standard',
            33170 => 'Packet Express',
            33197 => 'Packet Mini',
            28 => 'SRP',
            32 => 'SRM',
            33 => 'Courier Express',
            3440 => 'Priority',
            3441 => 'FirstClass',
            3442 => 'Priority International',
            3443 => 'FirstClass International',
            03 => 'UPS Ground',
            04 => 'Fedex Ground',
            33163 => 'SL Standard Modal',
            33171 => 'SL Express Modal',
            33198 => 'SL Small Parcels',
            33164 => 'AJ Packet Standard',
            33172 => 'AJ Packet Express',
            44162 => 'Colombia Urbano',
            44163 => 'Colombia Nacional',
            44165 => 'Colombia Trayetos',
            100 => 'Brazil Redispatch',
            537 => 'Global eParcel Prime',
            540 => 'Global eParcel Untracked Packet',
            773 => 'Prime5',
            05 => 'USPS Ground',
            734 => 'Post Plus Registered',
            367 => 'Post Plus EMS',
            541 => 'Parcel Post',
            777 => 'Post Plus Prime',
            778 => 'PrimeRIO',
            779 => 'DirectLink Australia',
            780 => 'DirectLink Canada',
            781 => 'DirectLink Chile',
            782 => 'DirectLink Mexico',
            357 => 'Prime5RIO',
            477 => 'GSS PMI',
            37634 => 'GSS EPMEI',
            3674 => 'GSS EPMI',
            3326 => 'GSS FCM',
            4367 => 'GSS EMS',
            4387 => 'GDE Priority Mail',
            4388 => 'GDE First Class',
            283 => 'Total Express',
            33173 => 'HD Express',
            776 => 'LT Prime',
            887 => 'Hound Express',
            44164 => 'Packet Standard B',
            44172 => 'Packet Express B',
            34166 => "AJ China Standard",
            33174 => "AJ China Express",
            587 => "PostPlus Portugal",
            588 => "PostPlus Colombia EMS",
            582 => "PostPlus Colombia Reg",
            5537 => 'Japan Prime JerseyPost',
            5541 => 'Japan EMS JerseyPost',
            237 => 'GSS CEP',
            238 => 'PasarEX',
            44166 => 'Colombia One Zone',

        ]
    ]
];