<?php

namespace App\Services\Colombia;

use App\Models\ShippingService;

class ColombiaPostalCodes
{
    public function getServiceByPostalCode($postalCode)
    {
        if ($this->nacionalService()->contains($postalCode)) {
            return ShippingService::COLOMBIA_NACIONAL;
        }

        if ($this->urbanoService()->contains($postalCode)) {
            return ShippingService::COLOMBIA_URBANO;
        }

        if ($this->trayetoService()->contains($postalCode)) {
            return ShippingService::COLOMBIA_TRAYETOS;
        }
        return null;
    }

    public function getPostalData()
    {
        $data = [];
        $cities = $this->colombiaCities()->toArray();
        $data = array_merge(['cities' => $cities]);
        return $data;
    }

    // public function getDepartment($city)
    // {
    //     $department = [];
    //     $cities = $this->colombiaCities();
    //     $depts = $this->colombiaDepts();
    //     $data = $cities->zip($depts)->toArray();
    //     foreach ($data as $key => $val) {
    //         if ($val[0] === $city) {
    //             array_push($department, $val[1]);
    //         }
    //     }
    //     return $department;
    // } 

    public function getZipCodes($city)
    {
        $codes = [];
        $cities = $this->colombiaCities();
        $zipCodes = $this->colombiaZipCodes();
        $data = $cities->zip($zipCodes)->toArray();
        foreach ($data as $key => $val) {
            if ($val[0] === $city) {
                array_push($codes, $val[1]);
            }
        }
        return $codes;
    }

    private function nacionalService()
    {
        $nacionalServiceCodes  = [
            '5001000',
            '5031000',
            '5045000',
            '5055000',
            '5079000',
            '5088000',
            '5147000',
            '5148000',
            '5154000',
            '5212000',
            '5264000',
            '5266000',
            '5360000',
            '5376000',
            '5380000',
            '5440000',
            '5591000',
            '5607000',
            '5615000',
            '5631000',
            '5659000',
            '5686000',
            '5697000',
            '5736000',
            '5756000',
            '5789000',
            '5837000',
            '5847000',
            '5895000',
            '8001000',
            '8573000',
            '8638000',
            '8758000',
            '1300100',
            '1324400',
            '1343000',
            '1383600',
            '1500100',
            '1517600',
            '1523800',
            '1529900',
            '1546900',
            '1551600',
            '1559900',
            '1575700',
            '1575900',
            '1580600',
            '1700100',
            '1704200',
            '1717400',
            '1727200',
            '1738000',
            '1777700',
            '1800100',
            '1900100',
            '1907500',
            '1914200',
            '1945500',
            '1957300',
            '1969800',
            '2000100',
            '2001100',
            '2006000',
            '2040000',
            '2051700',
            '2061400',
            '2300100',
            '2306800',
            '2316200',
            '2341700',
            '2341701',
            '2346600',
            '2355500',
            '2366000',
            '2504000',
            '2514800',
            '2515100',
            '2526000',
            '2529000',
            '2530700',
            '2532200',
            '2538600',
            '2540200',
            '2551300',
            '2577200',
            '2577700',
            '2587500',
            '4100100',
            '4129800',
            '4135700',
            '4139600',
            '4152400',
            '4154800',
            '4155100',
            '4400100',
            '4437800',
            '4443000',
            '4700100',
            '4718900',
            '4724500',
            '4728800',
            '5000100',
            '5000600',
            '5031300',
            '5056800',
            '5060600',
            '5068900',
            '5200100',
            '5208300',
            '5235600',
            '5283500',
            '5400100',
            '5400300',
            '5440500',
            '5449800',
            '5451800',
            '5487400',
            '6300100',
            '6313000',
            '6321200',
            '6327200',
            '6347000',
            '6600100',
            '6608800',
            '6617000',
            '6659400',
            '6668200',
            '6800100',
            '6807700',
            '6807900',
            '6808100',
            '6827600',
            '6854700',
            '6867900',
            '6875500',
            '6885500',
            '7000100',
            '7071700',
            '7300100',
            '7341100',
            '7344900',
            '7355500',
            '7362400',
            '7600100',
            '7610900',
            '7611100',
            '7611300',
            '7612600',
            '7613000',
            '7614700',
            '7624800',
            '7625000',
            '7627500',
            '7630600',
            '7636400',
            '7637700',
            '7652000',
            '7660600',
            '7673600',
            '7683400',
            '7689200',
            '7689500',
            '8500100',
            '8501000',
            '8516200',
            '8544000',
            '8600100',
            '8632000',
            '8676000',
            '8686500',
            '9500100',                                                           
        ];

        return collect($nacionalServiceCodes);
    }

    private function urbanoService()
    {
        $urbanoServiceCodes = [
            '11001000',
            '25126000',
            '25175000',
            '25214000',
            '25269000',
            '25286000',
            '25377000',
            '25430000',
            '25473000',
            '25754000',
            '25758000',
            '25817000',
            '25899000',                     
        ];

        return collect($urbanoServiceCodes);
    }

    private function trayetoService()
    {
        $trayetoServiceCodes = [
            '27001000',
            '81001000',
            '81300000',
            '81736000',
        ];

        return collect($trayetoServiceCodes);
    }

    private function colombiaCities()
    {
        $colombiaCities = [
            'MEDELLIN_ANTIOQUIA',
            'AMALFI',
            'APARTADO_ANTIOQUIA',
            'ARGELIA_ANTIOQUIA',
            'BARBOSA_ANTIOQUIA',
            'BELLO_ANTIOQUIA',
            'CAREPA',
            'EL CARMEN DE VIBORAL',
            'CAUCASIA',
            'COPACABANA',
            'ENTRERRIOS',
            'ENVIGADO',
            'ITAGUI',
            'LA CEJA_ANTIOQUIA',
            'LA ESTRELLA_ANTIOQUIA',
            'MARINILLA',
            'PUERTO TRIUNFO_ANTIOQUIA',
            'RETIRO_ANTIOQUIA',
            'RIONEGRO_ANTIOQUIA',
            'SABANETA_ANTIOQUIA',
            'SAN JUAN DE URABA',
            'SANTA ROSA DE OSOS',
            'EL SANTUARIO_ANTIOQUIA',
            'SEGOVIA_ANTIOQUIA',
            'SONSON',
            'TAMESIS',
            'TURBO',
            'URRAO',
            'ZARAGOZA_ANTIOQUIA',
            'BARRANQUILLA',
            'PUERTO COLOMBIA_ATLANTICO',
            'SABANALARGA_ATLANTICO',
            'SOLEDAD_ATLANTICO',
            'BOGOTA D.C.',
            'CARTAGENA_BOLIVAR',
            'EL CARMEN DE BOLIVAR',
            'MAGANGUE_BOLIVAR',
            'TURBACO',
            'TUNJA',
            'CHIQUINQUIRA_BOYACA',
            'DUITAMA',
            'GARAGOA_BOYACA',
            'MONIQUIRA_BOYACA',
            'PAIPA_BOYACA',
            'RAMIRIQUI_BOYACA',
            'SOCHA_BOYACA',
            'SOGAMOSO_BOYACA',
            'TIBASOSA_BOYACA',
            'MANIZALES_CALDAS',
            'ANSERMA',
            'CHINCHINA',
            'FILADELFIA_CALDAS',
            'LA DORADA_CALDAS',
            'SUPIA',
            'FLORENCIA_CAQUETA',
            'POPAYAN_CAUCA',
            'BALBOA_CAUCA',
            'CALOTO',
            'MIRANDA',
            'PUERTO TEJADA_CAUCA',
            'SANTANDER DE QUILICHAO',
            'VALLEDUPAR_CESAR',
            'AGUACHICA_CESAR',
            'BOSCONIA_CESAR',
            'LA JAGUA DE IBIRICO_CESAR',
            'PAILITAS_CESAR',
            'RIO DE ORO_CESAR',
            'MONTERIA_CORDOBA',
            'AYAPEL',
            'CERETE',
            'SANTA CRUZ DE LORICA_LORICA',
            'TIERRALTA_LORICA_CORDOBA',
            'MONTELIBANO',
            'PLANETA RICA',
            'SAHAGUN',
            'ANOLAIMA',
            'CAJICA',
            'CAPARRAPI',
            'CAQUEZA',
            'CHIA_CUNDINAMARCA',
            'COTA',
            'EL ROSAL_CUNDINAMARCA',
            'FACATATIVA_CUNDINAMARCA',
            'FUNZA',
            'FUSAGASUGA_CUNDINAMARCA',
            'GIRARDOT_CUNDINAMARCA',
            'GUASCA',
            'LA CALERA',
            'LA MESA_CUNDINAMARCA',
            'LA VEGA_CUNDINAMARCA',
            'MADRID',
            'MOSQUERA_CUNDINAMARCA',
            'PACHO',
            'SOACHA',
            'SOPO',
            'SUESCA',
            'SUPATA',
            'TOCANCIPA',
            'VILLETA',
            'ZIPAQUIRA',
            'QUIBDO',
            'NEIVA_HUILA',
            'GARZON_HUILA',
            'IQUIRA',
            'LA PLATA_HUILA',
            'PALERMO_HUILA',
            'PITAL_HUILA',
            'PITALITO_HUILA',
            'RIOHACHA',
            'HATONUEVO',
            'MAICAO',
            'SANTA MARTA_MAGDALENA',
            'CIENAGA',
            'EL BANCO_MAGDALENA',
            'FUNDACION_MAGDALENA',
            'VILLAVICENCIO_META',
            'ACACIAS_META',
            'GRANADA_META',
            'PUERTO GAITAN_META',
            'RESTREPO_META',
            'SAN MARTIN_META',
            'PASTO',
            'BELEN_NARIÑO',
            'IPIALES',
            'TUMACO_SAN ANDRES DE TUMACO',
            'CUCUTA_NORTE DE SANTANDER',
            'ABREGO_NORTE DE SANTANDER',
            'LOS PATIOS_NORTE DE SANTANDER',
            'OCAÑA_NORTE DE SANTANDER',
            'PAMPLONA_NORTE DE SANTANDER',
            'VILLA DEL ROSARIO_NORTE DE SANTANDER',
            'ARMENIA_QUINDIO',
            'CALARCA',
            'CORDOBA_QUINDIO',
            'FILANDIA',
            'MONTENEGRO',
            'PEREIRA_RISARALDA',
            'BELEN DE UMBRIA_RISARALDA',
            'DOSQUEBRADAS_RISARALDA',
            'QUINCHIA_RISARALDA',
            'SANTA ROSA DE CABAL',
            'BUCARAMANGA_SANTANDER',
            'BARBOSA_SANTANDER',
            'BARICHARA_SANTANDER',
            'BARRANCABERMEJA_SANTANDER',
            'FLORIDABLANCA_SANTANDER',
            'PIEDECUESTA_SANTANDER',
            'SAN GIL_SANTANDER',
            'SOCORRO_SANTANDER',
            'VALLE DE SAN JOSE_SANTANDER',
            'SINCELEJO',
            'SAN PEDRO_SUCRE',
            'IBAGUE',
            'LIBANO_TOLIMA',
            'MELGAR_TOLIMA',
            'PLANADAS_TOLIMA',
            'ROVIRA_TOLIMA',
            'CALI',
            'BUENAVENTURA',
            'BUGA',
            'BUGALAGRANDE',
            'DARIEN_CALIMA',
            'CANDELARIA_VALLE DEL CAUCA',
            'CARTAGO',
            'EL CERRITO_VALLE DEL CAUCA',
            'EL DOVIO',
            'FLORIDA_VALLE DEL CAUCA',
            'GINEBRA',
            'JAMUNDI',
            'LA CUMBRE_VALLE DEL CAUCA',
            'PALMIRA_VALLE DEL CAUCA',
            'RESTREPO_VALLE DEL CAUCA',
            'SEVILLA_VALLE DEL CAUCA',
            'TULUA',
            'YUMBO',
            'ZARZAL',
            'ARAUCA_ARAUCA',
            'FORTUL_ARAUCA',
            'SARAVENA_ARAUCA',
            'YOPAL',
            'AGUAZUL_CASANARE',
            'MONTERREY_CASANARE',
            'VILLANUEVA_CASANARE',
            'MOCOA',
            'ORITO',
            'SANTIAGO_PUTUMAYO',
            'LA HORMIGA_VALLE DEL GUAMUEZ',
            'SAN JOSE DEL GUAVIARE',
        ];

        return collect($colombiaCities);
    }

    private function colombiaDepts()
    {
        $colombiaDepts = [ 
            'QUINDIO',
            'ATLANTICO',
            'BOGOTA',
            'SANTANDER',
            'VALLE DEL CAUCA',
            'NORTE DE SANTANDER',
            'TOLIMA',
            'CALDAS',
            'ANTIOQUIA',
            'CORDOBA',
            'HUILA',
            'RISARALDA',
            'CAUCA',
            'BOYACA',
            'META',
            'CASANARE',
            'ANTIOQUIA',
            'NORTE DE SANTANDER',
            'ANTIOQUIA',
            'META',
            'CHOCO',
            'HUILA',
            'BOLIVAR',
            'HUILA',
            'CUNDINAMARCA',
            'CESAR',
            'SANTANDER',
            'CALDAS',
            'CASANARE',
            'CESAR',
            'HUILA',
            'CUNDINAMARCA',
            'SAN JOSE NARIÑO',
            'CAQUETA',
            'GUAJIRA',
            'SANTANDER',
            'VALLE DEL CAUCA',
            'NARIÑO',
            'ANTIOQUIA',
            'MAGDALENA',
            'HUILA',
            'CAUCA',
            'BOYACA',
            'TOLIMA',
            'HUILA',
            'CHOCO',
            'BOLIVAR',
            'TOLIMA',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'TOLIMA',
            'CUNDINAMARCA',
            'NARIÑO',
            'VALLE DEL CAUCA',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'ANTIOQUIA',
            'CALDAS',
            'VALLE DEL CAUCA',
            'ANTIOQUIA',
            'TOLIMA',
            'ANTIOQUIA',
            'RISARALDA',
            'CUNDINAMARCA',
            'BOYACA',
            'MAGDALENA',
            'CALDAS',
            'SANTANDER',
            'ARAUCA',
            'ARAUCA',
            'CUNDINAMARCA',
            'BERRUECOS NARIÑO',
            'NORTE DE SANTANDER',
            'ANTIOQUIA',
            'BOYACA',
            'BOLIVAR',
            'ANTIOQUIA',
            'CAUCA',
            'VALLE DEL CAUCA',
            'EL DIFICIL MAGDALENA',
            'BOLIVAR',
            'ANTIOQUIA',
            'GUAYABAL TOLIMA',
            'BOLIVAR',
            'CESAR',
            'TOLIMA',
            'YUTO CHOCO',
            'CORDOBA',
            'CHOCO',
            'CHOCO',
            'PIZARRO CHOCO',
            'CAUCA',
            'RISARALDA',
            'ATLANTICO',
            'HUILA',
            'NARIÑO',
            'ANTIOQUIA',
            'SANTANDER',
            'SANTANDER',
            'META',
            'SANTANDER',
            'GUAJIRA',
            'BOLIVAR',
            'CESAR',
            'CALDAS',
            'CAQUETA',
            'RISARALDA',
            'BOYACA',
            'NARIÑO',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'BOYACA',
            'ANTIOQUIA',
            'BOYACA',
            'ANTIOQUIA',
            'SANTANDER',
            'CUNDINAMARCA',
            'BOYACA',
            'NORTE DE SANTANDER',
            'CUNDINAMARCA',
            'BELLAVISTA CHOCO',
            'CAUCA',
            'SANTANDER',
            'VALLE DEL CAUCA',
            'CESAR',
            'BOYACA',
            'ANTIOQUIA',
            'BOYACA',
            'NORTE DE SANTANDER',
            'VALLE DEL CAUCA',
            'BOYACA',
            'CORDOBA',
            'QUINDIO',
            'SUCRE',
            'CAUCA',
            'NARIÑO',
            'VALLE DEL CAUCA',
            'VALLE DEL CAUCA',
            'ANTIOQUIA',
            'BOYACA',
            'CUNDINAMARCA',
            'SANTANDER',
            'META',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'NORTE DE SANTANDER',
            'NORTE DE SANTANDER',
            'ANTIOQUIA',
            'VALLE DEL CAUCA',
            'SUCRE',
            'TOLIMA',
            'CAUCA',
            'CUNDINAMARCA',
            'BOLIVAR',
            'GUAVIARE',
            'QUINDIO',
            'ANTIOQUIA',
            'BOYACA',
            'CAUCA',
            'SANTANDER',
            'CAUCA',
            'ANTIOQUIA',
            'ATLANTICO',
            'HUILA',
            'BOYACA',
            'CORDOBA',
            'ATLANTICO',
            'VALLE DEL CAUCA',
            'BOLIVAR',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'SANTANDER',
            'CUNDINAMARCA',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'SANTANDER',
            'ANTIOQUIA',
            'TOLIMA',
            'CUNDINAMARCA',
            'CURBARADO CHOCO',
            'ANTIOQUIA',
            'CAQUETA',
            'BOLIVAR',
            'VALLE DEL CAUCA',
            'VAUPES',
            'TOLIMA',
            'META',
            'ANTIOQUIA',
            'SANTANDER',
            'CORDOBA',
            'BOYACA',
            'SANTANDER',
            'MAGDALENA',
            'CHOCO',
            'NARIÑO',
            'CUNDINAMARCA',
            'SUCRE',
            'CASANARE',
            'TOLIMA',
            'SANTANDER',
            'SANTANDER',
            'CUNDINAMARCA',
            'MAGDALENA',
            'ANTIOQUIA',
            'CORDOBA',
            'SANTANDER',
            'CESAR',
            'NORTE DE SANTANDER',
            'BOYACA',
            'CALDAS',
            'CORDOBA',
            'CUNDINAMARCA',
            'SANTANDER',
            'BOYACA',
            'BOYACA',
            'CESAR',
            'BOYACA',
            'BOYACA',
            'NORTE DE SANTANDER',
            'BOYACA',
            'BOYACA',
            'BOYACA',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'BOLIVAR',
            'CORDOBA',
            'MAGDALENA',
            'BOYACA',
            'SANTANDER',
            'QUINDIO',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'BOLIVAR',
            'ANTIOQUIA',
            'TOLIMA',
            'CUNDINAMARCA',
            'HUILA',
            'GENOVA NARIÑO',
            'PUTUMAYO',
            'RICAURTE SUCRE',
            'BOYACA',
            'ANTIOQUIA',
            'SANTANDER',
            'ANTIOQUIA',
            'MAGDALENA',
            'CHOCO',
            'SANTANDER',
            'NARIÑO',
            'NARIÑO',
            'SANTANDER',
            'NORTE DE SANTANDER',
            'ANTIOQUIA',
            'BOYACA',
            'BOLIVAR',
            'NARIÑO',
            'QUINDIO',
            'CAUCA',
            'SANTANDER',
            'SUCRE',
            'BOYACA',
            'CUNDINAMARCA',
            'CORDOBA',
            'BOYACA',
            'SUCRE',
            'TOLIMA',
            'ARAUCA',
            'CARLOSAMA NARIÑO',
            'BOYACA',
            'META',
            'BOYACA',
            'CUNDINAMARCA',
            'NORTE DE SANTANDER',
            'BOYACA',
            'META',
            'VICHADA',
            'NARIÑO',
            'NARIÑO',
            'TOLIMA',
            'CAQUETA',
            'SANTANDER',
            'CESAR',
            'ANTIOQUIA',
            'VALLE DEL CAUCA',
            'CALIMA VALLE DEL CAUCA',
            'GUAJIRA',
            'GUAJIRA',
            'TOLIMA',
            'ANTIOQUIA',
            'RISARALDA',
            'BOYACA',
            'NORTE DE SANTANDER',
            'ANTIOQUIA',
            'VALLE DEL CAUCA',
            'ANTIOQUIA',
            'MAGDALENA',
            'CAUCA',
            'VALLE DEL CAUCA',
            'META',
            'MANAGRU CHOCO',
            'CHOCO',
            'BOLIVAR',
            'SANTANDER',
            'ANTIOQUIA',
            'NORTE DE SANTANDER',
            'META',
            'VALLE DEL CAUCA',
            'NARIÑO',
            'BOYACA',
            'CUNDINAMARCA',
            'CESAR',
            'CAQUETA',
            'META',
            'VALLE DEL CAUCA',
            'BOYACA',
            'SANTANDER',
            'BOLIVAR',
            'GUAJIRA',
            'CESAR',
            'CAQUETA',
            'NARIÑO',
            'BOLIVAR',
            'CUNDINAMARCA',
            'SANTANDER',
            'MAGDALENA',
            'SANTANDER',
            'MAGDALENA',
            'GUAVIARE',
            'SUCRE',
            'CUNDINAMARCA',
            'NARIÑO',
            'ANTIOQUIA',
            'NARIÑO',
            'CAUCA',
            'NARIÑO',
            'NORTE DE SANTANDER',
            'NORTE DE SANTANDER',
            'HUILA',
            'SANTANDER',
            'SANTANDER',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'TOLIMA',
            'CUNDINAMARCA',
            'TOLIMA',
            'CALDAS',
            'QUINDIO',
            'BOYACA',
            'TOLIMA',
            'CAQUETA',
            'CAUCA',
            'BOYACA',
            'SANTANDER',
            'VALLE DEL CAUCA',
            'SANTANDER',
            'CUNDINAMARCA',
            'GUAJIRA',
            'ARAUCA',
            'CUNDINAMARCA',
            'SALAHONDA NARIÑO',
            'ANTIOQUIA',
            'TOLIMA',
            'ANTIOQUIA',
            'META',
            'MAGDALENA',
            'NARIÑO',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'BOYACA',
            'CUNDINAMARCA',
            'SANTANDER',
            'ATLANTICO',
            'SUCRE',
            'CUNDINAMARCA',
            'CESAR',
            'SANTANDER',
            'BOYACA',
            'BOYACA',
            'HUILA',
            'QUINDIO',
            'HUILA',
            'VALLE DEL CAUCA',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'ANTIOQUIA',
            'SANTANDER',
            'ANTIOQUIA',
            'CESAR',
            'NORTE DE SANTANDER',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'META',
            'SANTANDER',
            'BOYACA',
            'VALLE DEL CAUCA',
            'CAUCA',
            'CUNDINAMARCA',
            'NARIÑO',
            'ANTIOQUIA',
            'HUILA',
            'SANTANDER',
            'CUNDINAMARCA',
            'NARIÑO',
            'NARIÑO',
            'MAGDALENA',
            'META',
            'TOLIMA',
            'CAUCA',
            'SANTANDER',
            'SUCRE',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'BOYACA',
            'RISARALDA',
            'SANTANDER',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'BOYACA',
            'SANTANDER',
            'BOYACA',
            'CUNDINAMARCA',
            'NORTE DE SANTANDER',
            'BOLIVAR',
            'CASANARE',
            'SANTANDER',
            'GUAJIRA',
            'ANTIOQUIA',
            'NORTE DE SANTANDER',
            'TOLIMA',
            'ANTIOQUIA',
            'HUILA',
            'TOLIMA',
            'TOLIMA',
            'NARIÑO',
            'NARIÑO',
            'GUAINIA',
            'CAUCA',
            'NARIÑO',
            'HUILA',
            'SANTA BARBARA NARIÑO',
            'HUILA',
            'CHOCO',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'BOYACA',
            'CAUCA',
            'VALLE DEL CAUCA',
            'ANTIOQUIA',
            'BOYACA',
            'ANTIOQUIA',
            'BOYACA',
            'CUNDINAMARCA',
            'SANTANDER',
            'SANTANDER',
            'ATLANTICO',
            'CUNDINAMARCA',
            'CHOCO',
            'CORDOBA',
            'HUILA',
            'SANTANDER',
            'CUNDINAMARCA',
            'BOYACA',
            'ANTIOQUIA',
            'RISARALDA',
            'NARIÑO',
            'VALLE DEL CAUCA',
            'CALDAS',
            'NORTE DE SANTANDER',
            'ANTIOQUIA',
            'NARIÑO',
            'CESAR',
            'CESAR',
            'GUAJIRA',
            'NARIÑO',
            'META',
            'CALDAS',
            'CUNDINAMARCA',
            'CAQUETA',
            'CUNDINAMARCA',
            'ROBLES CESAR',
            'SANTANDER',
            'CUNDINAMARCA',
            'ANTIOQUIA',
            'HUILA',
            'NORTE DE SANTANDER',
            'VICHADA',
            'CASANARE',
            'CAUCA',
            'QUINDIO',
            'NARIÑO',
            'ANTIOQUIA',
            'NARIÑO',
            'SUCRE',
            'VALLE DEL CAUCA',
            'BOYACA',
            'CAUCA',
            'CUNDINAMARCA',
            'BOYACA',
            'VALLE DEL CAUCA',
            'RISARALDA',
            'NORTE DE SANTANDER',
            'BOYACA',
            'SANTANDER',
            'SANTANDER',
            'PUTUMAYO',
            'NARIÑO',
            'META',
            'CUNDINAMARCA',
            'TOLIMA',
            'AMAZONAS',
            'TOLIMA',
            'ANTIOQUIA',
            'NARIÑO',
            'CHOCO',
            'MICAY CAUCA',
            'CORDOBA',
            'SOTOMAYOR NARIÑO',
            'CORDOBA',
            'SUCRE',
            'NORTE DE SANTANDER',
            'SANTANDER',
            'NORTE DE SANTANDER',
            'ATLANTICO',
            'BOYACA',
            'SANTANDER',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'BOLIVAR',
            'PAYAN NARIÑO',
            'BOLIVAR',
            'GUAJIRA',
            'SUCRE',
            'SANTANDER',
            'ATLANTICO',
            'PIEDRANCHA NARIÑO',
            'ATLANTICO',
            'GUAJIRA',
            'BALCON DEL CESAR CESAR',
            'CASANARE',
            'CUNDINAMARCA',
            'CALDAS',
            'META',
            'BOLIVAR',
            'BOLIVAR',
            'ANTIOQUIA',
            'BOYACA',
            'TOLIMA',
            'CALDAS',
            'CALDAS',
            'RISARALDA',
            'CALDAS',
            'SANTANDER',
            'CUNDINAMARCA',
            'BETE CHOCO',
            'CHOCO',
            'ANDAGOYA CHOCO',
            'TOLIMA',
            'CAUCA',
            'META',
            'CAQUETA',
            'BOYACA',
            'GUAVIARE',
            'CAUCA',
            'RISARALDA',
            'VAUPES',
            'PUTUMAYO',
            'SANTANDER',
            'SANTANDER',
            'CORDOBA',
            'BOLIVAR',
            'BOYACA',
            'BOYACA',
            'BOYACA',
            'ANTIOQUIA',
            'BOLIVAR',
            'CORDOBA',
            'QUINDIO',
            'CASANARE',
            'CORDOBA',
            'BOLIVAR',
            'CAUCA',
            'CAQUETA',
            'SUCRE',
            'CUNDINAMARCA',
            'NARIÑO',
            'BOYACA',
            'TOLIMA',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'NORTE DE SANTANDER',
            'BOYACA',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'NARIÑO',
            'HUILA',
            'TOLIMA',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'CALDAS',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'BOYACA',
            'CUNDINAMARCA',
            'CALDAS',
            'BOLIVAR',
            'CHOCO',
            'MAGDALENA',
            'BOYACA',
            'CASANARE',
            'CHOCO',
            'VALLE DEL CAUCA',
            'SANTANDER',
            'NORTE DE SANTANDER',
            'SANTANDER',
            'BOYACA',
            'BOCAS DE SATINGA NARIÑO',
            'ANTIOQUIA',
            'SANTANDER',
            'HUILA',
            'PUTUMAYO',
            'CASANARE',
            'TOLIMA',
            'NARIÑO',
            'BOYACA',
            'SUCRE',
            'BOYACA',
            'CUNDINAMARCA',
            'CALDAS',
            'CAUCA',
            'BELALCAZAR CAUCA',
            'BOYACA',
            'HUILA',
            'CESAR',
            'CUNDINAMARCA',
            'BOYACA',
            'BOYACA',
            'HUILA',
            'CALDAS',
            'HUILA',
            'ATLANTICO',
            'SANTANDER',
            'SANTANDER',
            'VALLE DEL CAUCA',
            'SUCRE',
            'TOLIMA',
            'NORTE DE SANTANDER',
            'NORTE DE SANTANDER',
            'CUNDINAMARCA',
            'BOYACA',
            'SANTANDER',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'NARIÑO',
            'BOYACA',
            'BOYACA',
            'CASANARE',
            'BOYACA',
            'MAGDALENA',
            'CESAR',
            'CALDAS',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'BOYACA',
            'CAUCA',
            'SANTANDER',
            'TOLIMA',
            'CAUCA',
            'QUINDIO',
            'MAGDALENA',
            'SANTANDER',
            'BOLIVAR',
            'ATLANTICO',
            'BOYACA',
            'HUILA',
            'HUILA',
            'MAGDALENA',
            'TOLIMA',
            'CORDOBA',
            'MAGDALENA',
            'NARIÑO',
            'ATLANTICO',
            'ATLANTICO',
            'CASANARE',
            'NARIÑO',
            'VALLE DEL CAUCA',
            'TOLIMA',
            'NARIÑO',
            'SAN ANDRES',
            'CESAR',
            'CORDOBA',
            'RISARALDA',
            'ANTIOQUIA',
            'MAGDALENA',
            'SANTANDER',
            'NARIÑO',
            'PUTUMAYO',
            'ANTIOQUIA',
            'BOYACA',
            'PUTUMAYO',
            'VICHADA',
            'ATLANTICO',
            'META',
            'CORDOBA',
            'META',
            'PUTUMAYO',
            'CORDOBA',
            'META',
            'META',
            'ANTIOQUIA',
            'AMAZONAS',
            'SANTANDER',
            'CAQUETA',
            'META',
            'ARAUCA',
            'CUNDINAMARCA',
            'NORTE DE SANTANDER',
            'CAUCA',
            'ANTIOQUIA',
            'SANTANDER',
            'CUNDINAMARCA',
            'NARIÑO',
            'COCONUCO CAUCA',
            'TOLIMA',
            'CORDOBA',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'CHOCO',
            'QUINDIO',
            'RISARALDA',
            'BOYACA',
            'CUNDINAMARCA',
            'NORTE DE SANTANDER',
            'BOYACA',
            'BOYACA',
            'CASANARE',
            'BOLIVAR',
            'ANTIOQUIA',
            'MAGDALENA',
            'ATLANTICO',
            'META',
            'VALLE DEL CAUCA',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'NARIÑO',
            'CESAR',
            'SANTA RITA CHOCO',
            'PAIMADO CHOCO',
            'BOLIVAR',
            'TOLIMA',
            'VALLE DEL CAUCA',
            'GUAJIRA',
            'ANTIOQUIA',
            'SANTANDER',
            'CALDAS',
            'CHOCO',
            'CALDAS',
            'HUILA',
            'SAN JOSE NARIÑO',
            'VALLE DEL CAUCA',
            'TOLIMA',
            'BOYACA',
            'CAUCA',
            'TOLIMA',
            'SANTANDER',
            'ATLANTICO',
            'ANTIOQUIA',
            'ATLANTICO',
            'CASANARE',
            'MAGDALENA',
            'ANTIOQUIA',
            'BOYACA',
            'CASANARE',
            'BOYACA',
            'CORDOBA',
            'HUILA',
            'CALDAS',
            'MAGDALENA',
            'NORTE DE SANTANDER',
            'TOLIMA',
            'QUINDIO',
            'ANTIOQUIA',
            'BOYACA',
            'CALDAS',
            'NARIÑO',
            'SUCRE',
            'HUILA',
            'CESAR',
            'ANTIOQUIA',
            'CORDOBA',
            'SAN ANDRES',
            'SANTANDER',
            'CORDOBA',
            'CUNDINAMARCA',
            'TOLIMA',
            'SUCRE',
            'SANTANDER',
            'CORDOBA',
            'CUNDINAMARCA',
            'NARIÑO',
            'NORTE DE SANTANDER',
            'META',
            'ANTIOQUIA',
            'CORDOBA',
            'NORTE DE SANTANDER',
            'PUEBLO NUEVO CUNDINAMARCA',
            'BOLIVAR',
            'CESAR',
            'BOYACA',
            'BOLIVAR',
            'BOLIVAR',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'PUTUMAYO',
            'SANTANDER',
            'BOLIVAR',
            'BOLIVAR',
            'ANTIOQUIA',
            'SANTANDER',
            'ANTIOQUIA',
            'SANTANDER',
            'BOYACA',
            'CORDOBA',
            'CAQUETA',
            'GUAVIARE',
            'CHOCO',
            'CALDAS',
            'EL LITORAL DEL SAN JUAN CHOCO',
            'META',
            'SUCRE',
            'CUNDINAMARCA',
            'ANTIOQUIA',
            'GUAJIRA',
            'BOLIVAR',
            'META',
            'NARIÑO',
            'BOYACA',
            'CASANARE',
            'SUCRE',
            'ANTIOQUIA',
            'TOLIMA',
            'SUCRE',
            'BOLIVAR',
            'CESAR',
            'META',
            'BOYACA',
            'BOYACA',
            'PUTUMAYO',
            'SANTANDER',
            'SUCRE',
            'BOYACA',
            'BOLIVAR',
            'NARIÑO',
            'NARIÑO',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'SUCRE',
            'VALLE DEL CAUCA',
            'CORDOBA',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'MAGDALENA',
            'CAUCA',
            'SANTANDER',
            'CAQUETA',
            'ANTIOQUIA',
            'MAGDALENA',
            'NARIÑO',
            'MAGDALENA',
            'MAGDALENA',
            'ANTIOQUIA',
            'SANTANDER',
            'BOLIVAR',
            'SANTANDER',
            'TOLIMA',
            'ATLANTICO',
            'BOYACA',
            'HUILA',
            'MAGDALENA',
            'RISARALDA',
            'ANTIOQUIA',
            'BOYACA',
            'BOLIVAR',
            'CAUCA',
            'SANTA ROSA DE LIMA BOLIVAR',
            'VICHADA',
            'BOYACA',
            'GUACHAVES NARIÑO',
            'ANTIOQUIA',
            'BOYACA',
            'CAUCA',
            'SUCRE',
            'NORTE DE SANTANDER',
            'PUTUMAYO',
            'ANTIOQUIA',
            'ATLANTICO',
            'RISARALDA',
            'NARIÑO',
            'ARAUCA',
            'NORTE DE SANTANDER',
            'CUNDINAMARCA',
            'BOYACA',
            'BOYACA',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'VALLE DEL CAUCA',
            'ZONA BANANERA MAGDALENA',
            'BOYACA',
            'CUNDINAMARCA',
            'PUTUMAYO',
            'NORTE DE SANTANDER',
            'CUNDINAMARCA',
            'CAUCA',
            'SANTANDER',
            'CUNDINAMARCA',
            'BOLIVAR',
            'SUCRE',
            'CHOCO',
            'MAGDALENA',
            'CUNDINAMARCA',
            'BOYACA',
            'BOYACA',
            'SANTANDER',
            'BOYACA',
            'BOYACA',
            'CAQUETA',
            'ATLANTICO',
            'CAQUETA',
            'BOYACA',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'BOLIVAR',
            'CUNDINAMARCA',
            'BOYACA',
            'BOYACA',
            'BOYACA',
            'PAISPAMBA CAUCA',
            'SANTANDER',
            'ATLANTICO',
            'CAUCA',
            'TOLIMA',
            'HUILA',
            'CUNDINAMARCA',
            'CAUCA',
            'SANTANDER',
            'SUCRE',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'CALDAS',
            'SANTANDER',
            'CUNDINAMARCA',
            'BOYACA',
            'BOYACA',
            'CUNDINAMARCA',
            'BOYACA',
            'CUNDINAMARCA',
            'CHOCO',
            'BOLIVAR',
            'CESAR',
            'CASANARE',
            'ARAUCA',
            'ANTIOQUIA',
            'NARIÑO',
            'NARIÑO',
            'VAUPES',
            'ANTIOQUIA',
            'HUILA',
            'ANTIOQUIA',
            'BOYACA',
            'CASANARE',
            'CUNDINAMARCA',
            'HUILA',
            'CUNDINAMARCA',
            'MAGDALENA',
            'CUNDINAMARCA',
            'BOYACA',
            'NORTE DE SANTANDER',
            'HUILA',
            'HUILA',
            'CUNDINAMARCA',
            'BOYACA',
            'BOYACA',
            'CUNDINAMARCA',
            'NORTE DE SANTANDER',
            'CORDOBA',
            'HUILA',
            'CAUCA',
            'CAUCA',
            'BOYACA',
            'BOYACA',
            'PUERTO RICO BOLIVAR',
            'ANTIOQUIA',
            'BOYACA',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'BOYACA',
            'ANTIOQUIA',
            'NORTE DE SANTANDER',
            'SUCRE',
            'SANTANDER',
            'BOYACA',
            'CUNDINAMARCA',
            'CAUCA',
            'VALLE DEL CAUCA',
            'BOYACA',
            'CAUCA',
            'CASANARE',
            'VALLE DEL CAUCA',
            'ATLANTICO',
            'CORDOBA',
            'VALLE DEL CAUCA',
            'SAN ANDRES DE TUMACO NARIÑO',
            'BOYACA',
            'NARIÑO',
            'BOLIVAR',
            'BOLIVAR',
            'ANTIOQUIA',
            'BOYACA',
            'BOYACA',
            'BOYACA',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'VALLE DEL CAUCA',
            'BOYACA',
            'CUNDINAMARCA',
            'CHOCO',
            'ANIMAS CHOCO',
            'ANTIOQUIA',
            'META',
            'GUAJIRA',
            'ANTIOQUIA',
            'GUAJIRA',
            'ATLANTICO',
            'CUNDINAMARCA',
            'ANTIOQUIA',
            'CORDOBA',
            'SANTANDER',
            'TOLIMA',
            'LA HORMIGA PUTUMAYO',
            'CESAR',
            'ANTIOQUIA',
            'CAQUETA',
            'ANTIOQUIA',
            'SANTANDER',
            'TOLIMA',
            'ANTIOQUIA',
            'CUNDINAMARCA',
            'BOYACA',
            'CUNDINAMARCA',
            'VALLE DEL CAUCA',
            'SANTANDER',
            'CUNDINAMARCA',
            'CALDAS',
            'ANTIOQUIA',
            'VALLE DEL CAUCA',
            'NORTE DE SANTANDER',
            'BOYACA',
            'NORTE DE SANTANDER',
            'CAUCA',
            'PUTUMAYO',
            'CUNDINAMARCA',
            'TOLIMA',
            'CALDAS',
            'BOLIVAR',
            'CASANARE',
            'GUAJIRA',
            'SANTANDER',
            'CUNDINAMARCA',
            'TOLIMA',
            'HUILA',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            'BOYACA',
            'META',
            'CALDAS',
            'CUNDINAMARCA',
            'NARIÑO',
            'HUILA',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'ANTIOQUIA',
            'CASABE ANTIOQUIA',
            'VALLE DEL CAUCA',
            'VALLE DEL CAUCA',
            'BOLIVAR',
            'SANTANDER',
            'PUNTA DE PIEDRAS MAGDALENA',
            'ANTIOQUIA',
            'VALLE DEL CAUCA',
            'BOYACA',
            'CUNDINAMARCA',
            'CUNDINAMARCA',
            '',
        ];
        return $colombiaDepts;
    }

    private function colombiaZipCodes()
    {
        $colombiaZipCodes = [ 
            '5001000',
            '5031000',
            '5045000',
            '5055000',
            '5079000',
            '5088000',
            '5147000',
            '5148000',
            '5154000',
            '5212000',
            '5264000',
            '5266000',
            '5360000',
            '5376000',
            '5380000',
            '5440000',
            '5591000',
            '5607000',
            '5615000',
            '5631000',
            '5659000',
            '5686000',
            '5697000',
            '5736000',
            '5756000',
            '5789000',
            '5837000',
            '5847000',
            '5895000',
            '8001000',
            '8573000',
            '8638000',
            '8758000',
            '11001000',
            '13001000',
            '13244000',
            '13430000',
            '13836000',
            '15001000',
            '15176000',
            '15238000',
            '15299000',
            '15469000',
            '15516000',
            '15599000',
            '15757000',
            '15759000',
            '15806000',
            '17001000',
            '17042000',
            '17174000',
            '17272000',
            '17380000',
            '17777000',
            '18001000',
            '19001000',
            '19075000',
            '19142000',
            '19455000',
            '19573000',
            '19698000',
            '20001000',
            '20011000',
            '20060000',
            '20400000',
            '20517000',
            '20614000',
            '23001000',
            '23068000',
            '23162000',
            '23417000',
            '23417010',
            '23466000',
            '23555000',
            '23660000',
            '25040000',
            '25126000',
            '25148000',
            '25151000',
            '25175000',
            '25214000',
            '25260000',
            '25269000',
            '25286000',
            '25290000',
            '25307000',
            '25322000',
            '25377000',
            '25386000',
            '25402000',
            '25430000',
            '25473000',
            '25513000',
            '25754000',
            '25758000',
            '25772000',
            '25777000',
            '25817000',
            '25875000',
            '25899000',
            '27001000',
            '41001000',
            '41298000',
            '41357000',
            '41396000',
            '41524000',
            '41548000',
            '41551000',
            '44001000',
            '44378000',
            '44430000',
            '47001000',
            '47189000',
            '47245000',
            '47288000',
            '50001000',
            '50006000',
            '50313000',
            '50568000',
            '50606000',
            '50689000',
            '52001000',
            '52083000',
            '52356000',
            '52835000',
            '54001000',
            '54003000',
            '54405000',
            '54498000',
            '54518000',
            '54874000',
            '63001000',
            '63130000',
            '63212000',
            '63272000',
            '63470000',
            '66001000',
            '66088000',
            '66170000',
            '66594000',
            '66682000',
            '68001000',
            '68077000',
            '68079000',
            '68081000',
            '68276000',
            '68547000',
            '68679000',
            '68755000',
            '68855000',
            '70001000',
            '70717000',
            '73001000',
            '73411000',
            '73449000',
            '73555000',
            '73624000',
            '76001000',
            '76109000',
            '76111000',
            '76113000',
            '76126000',
            '76130000',
            '76147000',
            '76248000',
            '76250000',
            '76275000',
            '76306000',
            '76364000',
            '76377000',
            '76520000',
            '76606000',
            '76736000',
            '76834000',
            '76892000',
            '76895000',
            '81001000',
            '81300000',
            '81736000',
            '85001000',
            '85010000',
            '85162000',
            '85440000',
            '86001000',
            '86320000',
            '86760000',
            '86865000',
            '95001000',
        ];
        return $colombiaZipCodes;
    }
}
