<?php

namespace App\Services\Excel\Export;
use App\Models\Order;
use App\Models\ShippingService;
use App\Models\Warehouse\AccrualRate;
use App\Models\Warehouse\Container;
use App\Models\Warehouse\DeliveryBill;

class ExportUsCustomerLabelManifest extends AbstractExportService
{
    private $currentRow = 1;
    private $deliveryBill;
    private $row = 0;
    private $totalCustomerPaid;
    private $totalPaidToCorreios;
    private $totalPieces = 0;
    private $totalWeight = 0;
    private $totalCommission = 0;
    private $totalAnjunCommission = 0;
    private $date;
    public function __construct(DeliveryBill $deliveryBill)
    {
        $this->deliveryBill = $deliveryBill;
        $this->date = $deliveryBill->created_at->format('m/d/Y"');
        parent::__construct();
    }   
    public function handle()
    {
        $this->prepareExcelSheet();
        return $this->downloadExcel();
    }
   
    private function prepareExcelSheet()
    { 
        $this->setExcelHeaderRow();        
        $row = $this->currentRow;
        foreach ($this->deliveryBill->containers as $container){
        foreach ($container->orders as $package) {
                 $this->setCellValue('A'.$row, 'Master');
                 $this->setCellValue('B'.$row, $container->awb);
                 $this->setCellValue('C'.$row, $container->awb);
                 $this->setCellValue('D'.$row, $container->awb);
                 $this->setCellValue('E'.$row, $package->corrios_tracking_code);  
                 $this->setCellValue('F'.$row, $container->origin_airport);  
                 $this->setCellValue('G'.$row, '');  
                 $this->setCellValue('H'.$row, $container->created_at->addDays(1));  
                 $this->setCellValue('I'.$row, '');  
                 $this->setCellValue('J'.$row, $container->destination_operator_name); 
                 $this->setCellValue('K'.$row, '');  
                 $this->setCellValue('L'.$row, $container->flight_number);  
                 $this->setCellValue('M'.$row, $container->created_at->addDays(1));   
                 $this->setCellValue('N'.$row, '');  
                 $this->setCellValue('O'.$row, count($this->deliveryBill->containers));
                 $this->setCellValue('P'.$row, $this->deliveryBill->getWeight());  
                 $this->setCellValue('Q'.$row, '');
                 $this->setCellValue('R'.$row, '');
                 $this->setCellValue('S'.$row, '');
                 $this->setCellValue('T'.$row, '');
                 $this->setCellValue('U'.$row, $package->getSenderFullName());
                 $this->setCellValue('V'.$row, ($package->sender_address) ? $package->sender_address: '2200 NW 129TH AVE');
                 $this->setCellValue('W'.$row, ($package->sender_city) ? $package->sender_city: 'Miami');
                 $this->setCellValue('X'.$row, ($package->sender_state_id) ? $package->senderState->code: 'FL');
                 $this->setCellValue('Y'.$row, ($package->sender_zipcode) ? $package->sender_zipcode: '33182');
                 $this->setCellValue('Z'.$row, ($package->sender_zipcode) ? $package->sender_zipcode: 'US');
                 $this->setCellValue('AA'.$row, $package->recipient->getFullName());
                 $this->setCellValue('AB'.$row, $package->warehouse_number);
                 $this->setCellValue('AC'.$row, ($package->sender_phone) ? $package->sender_phone: '');
                 $this->setCellValue('AD'.$row, ($package->recipient->tax_id) ? $package->recipient->tax_id: '');
                 $this->setCellValue('AE'.$row, $package->recipient->address.' '.optional($package->recipient)->address2.' '.$package->recipient->street_no);
                 $this->setCellValue('AF'.$row, $package->recipient->city);
                 $this->setCellValue('AG'.$row, $package->recipient->State->code);
                 $this->setCellValue('AH'.$row, $package->recipient->zipcode);
                 $this->setCellValue('AI'.$row, $package->recipient->country->code);
                 $this->setCellValue('AJ'.$row, $container->getPiecesCount());
                 $this->setCellValue('AK'.$row, $this->deliveryBill->getWeight());
                 $this->setCellValue('AL'.$row, 'KG');
                 $this->setCellValue('AM'.$row, ($package->recipient->phone) ? $package->recipient->phone: '',);
                 $this->setCellValue('AN'.$row, '');
                 $this->setCellValue('AO'.$row, '');
                 $this->setCellValue('AP'.$row, '');
                 $this->setCellValue('AQ'.$row, '');
                 $this->setCellValue('AR'.$row, '');
                 $this->setCellValue('AS'.$row, '');
                 $this->setCellValue('AT'.$row, '');
                 $this->setCellValue('AU'.$row, '');
                 $this->setCellValue('AV'.$row, '');
                 $this->setCellValue('AW'.$row, '');
                 $this->setCellValue('AX'.$row, '');
                 $this->setCellValue('AY'.$row, '');
                 $this->setCellValue('AZ'.$row, '');

                 $this->setCellValue('BA'.$row, '');
                 $this->setCellValue('BB'.$row, '');
                 $this->setCellValue('BC'.$row, '');
                 $this->setCellValue('BD'.$row, '');
                 $this->setCellValue('BE'.$row, '');
                 $this->setCellValue('BF'.$row, '');
                 $this->setCellValue('BH'.$row, '');
                 $this->setCellValue('BI'.$row, '');
                 $this->setCellValue('BJ'.$row, '');
                 $this->setCellValue('BK'.$row, '');
                 $this->setCellValue('BL'.$row, '');
                 $this->setCellValue('BM'.$row, '');
                 $this->setCellValue('BN'.$row, '');
                 $this->setCellValue('BO'.$row, '');
                 $this->setCellValue('BP'.$row, '');
                 $this->setCellValue('BQ'.$row, '');
                 $this->setCellValue('BR'.$row, '');
                 $this->setCellValue('BS'.$row, '');
                 $this->setCellValue('BT'.$row, '');
                 $this->setCellValue('BU'.$row, '');
                 $this->setCellValue('BV'.$row, '');
                 $this->setCellValue('BW'.$row, '');
                 $this->setCellValue('BX'.$row, '');
                 $this->setCellValue('BY'.$row, '');
                 $this->setCellValue('BZ'.$row, '');
                 
                 $this->setCellValue('CA'.$row, '');
                 $this->setCellValue('CB'.$row, '');
                 $this->setCellValue('CC'.$row, '');
                 $this->setCellValue('CD'.$row, '');
                 $this->setCellValue('CE'.$row, '');
                 $this->setCellValue('CF'.$row, '');
                 $this->setCellValue('CG'.$row, '');
                 $this->setCellValue('CH'.$row, '');
                 $this->setCellValue('CI'.$row, '');
                 $this->setCellValue('CJ'.$row, '');
                 $this->setCellValue('CK'.$row, '');
                 $this->setCellValue('CI'.$row, '');
                 $this->setCellValue('CJ'.$row, '');
                 $this->setCellValue('CK'.$row, '');
                 $this->setCellValue('CL'.$row, '');
                 $this->setCellValue('CM'.$row, '');
                 $this->setCellValue('CN'.$row, '');
                 $this->setCellValue('CO'.$row, '');
                 $this->setCellValue('CP'.$row, '');
                 $this->setCellValue('CQ'.$row, '');
                 $this->setCellValue('CR'.$row, '');
                 $this->setCellValue('CS'.$row, '');
                 $this->setCellValue('CT'.$row, '');
                 $this->setCellValue('CU'.$row, '');
                 $this->setCellValue('CV'.$row, '');
                 $this->setCellValue('CW'.$row, '');
                 $this->setCellValue('CX'.$row, '');
                 $this->setCellValue('CY'.$row, '');
                 $this->setCellValue('CZ'.$row, '');

                 $this->setCellValue('DA'.$row, '');
                 $this->setCellValue('DB'.$row, '');
                 $this->setCellValue('DC'.$row, '');
                 $this->setCellValue('DD'.$row, '');
                 $this->setCellValue('DE'.$row, '');
                 $this->setCellValue('DF'.$row, '');
                 $this->setCellValue('DG'.$row, '');
                 $this->setCellValue('DH'.$row, '');
                 $this->setCellValue('DI'.$row, '');
                 $this->setCellValue('DJ'.$row, '');
                 $this->setCellValue('DK'.$row, '');
                 $this->setCellValue('DI'.$row, '');
                 $this->setCellValue('DJ'.$row, '');
                 $this->setCellValue('DK'.$row, '');
                 $this->setCellValue('DL'.$row, '');
                 $this->setCellValue('DM'.$row, '');
                 $this->setCellValue('DN'.$row, '');
                 $this->setCellValue('DO'.$row, '');
                 $this->setCellValue('DP'.$row, '');
                 $this->setCellValue('DQ'.$row, '');
                 $this->setCellValue('DR'.$row, '');
                 $this->setCellValue('DS'.$row, '');
                 $this->setCellValue('DT'.$row, '');
                 $this->setCellValue('DU'.$row, '');
                 $this->setCellValue('DV'.$row, '');
                 $this->setCellValue('DW'.$row, '');
                 $this->setCellValue('DX'.$row, '');
                 $this->setCellValue('DY'.$row, '');
                 $this->setCellValue('DZ'.$row, '');
                 
                 $this->setCellValue('EA'.$row, '');
                 $this->setCellValue('EB'.$row, '');
                 $this->setCellValue('EC'.$row, '');
                 $this->setCellValue('ED'.$row, '');
                 $this->setCellValue('EE'.$row, '');
                 $this->setCellValue('EF'.$row, '');
                 $this->setCellValue('EG'.$row, '');
                 $this->setCellValue('EH'.$row, '');
                 $this->setCellValue('EI'.$row, '');
                 $this->setCellValue('EJ'.$row, '');
                 $this->setCellValue('EK'.$row, '');
                 $this->setCellValue('EI'.$row, '');
                 $this->setCellValue('EJ'.$row, '');
                 $this->setCellValue('EK'.$row, '');
                 $this->setCellValue('EL'.$row, '');
                 $this->setCellValue('EM'.$row, '');
                 $this->setCellValue('EN'.$row, '');
                 $this->setCellValue('EO'.$row, '');
                 $this->setCellValue('EP'.$row, '');
                 $this->setCellValue('EQ'.$row, '');
                 $this->setCellValue('ER'.$row, '');
                 $this->setCellValue('ES'.$row, '');
                 $this->setCellValue('ET'.$row, '');
                 $this->setCellValue('EU'.$row, '');
                 $this->setCellValue('EV'.$row, '');
                 $this->setCellValue('EW'.$row, '');
                 $this->setCellValue('EX'.$row, '');
                 $this->setCellValue('EY'.$row, '');
                 $this->setCellValue('EZ'.$row, '');

                 $this->setCellValue('FA'.$row, '');
                 $this->setCellValue('FB'.$row, '');
                 $this->setCellValue('FC'.$row, '');
                 $this->setCellValue('FD'.$row, '');
                 $this->setCellValue('FE'.$row, '');
                 $this->setCellValue('FF'.$row, '');
                 $this->setCellValue('FG'.$row, '');
                 $this->setCellValue('FH'.$row, '');
                 $this->setCellValue('FI'.$row, '');
                 $this->setCellValue('FJ'.$row, '');
                 $this->setCellValue('FK'.$row, '');
                 $this->setCellValue('FI'.$row, '');
                 $this->setCellValue('FJ'.$row, '');
                 $this->setCellValue('FK'.$row, '');
                 $this->setCellValue('FL'.$row, '');
                 $this->setCellValue('FM'.$row, '');
                 $this->setCellValue('FN'.$row, '');
                 $this->setCellValue('FO'.$row, '');
                 $this->setCellValue('FP'.$row, '');
                 $this->setCellValue('FQ'.$row, '');
                 $this->setCellValue('FR'.$row, '');
                 $this->setCellValue('FS'.$row, '');
                 $this->setCellValue('FT'.$row, '');
                 $this->setCellValue('FU'.$row, '');
                 $this->setCellValue('FV'.$row, '');
                 $this->setCellValue('FW'.$row, '');
                 $this->setCellValue('FX'.$row, '');
                 $this->setCellValue('FY'.$row, '');
                 $this->setCellValue('FZ'.$row, '');

                 $this->setCellValue('GA'.$row, '');
                 $this->setCellValue('GB'.$row, '');
                 $this->setCellValue('GC'.$row, '');
                 $this->setCellValue('GD'.$row, '');
                 $this->setCellValue('GE'.$row, '');
                 $this->setCellValue('GF'.$row, '');
                 $this->setCellValue('GG'.$row, '');
                 $this->setCellValue('GH'.$row, '');
                 $this->setCellValue('GI'.$row, '');
                 $this->setCellValue('GJ'.$row, '');
                 $this->setCellValue('GK'.$row, '');
                 $this->setCellValue('GI'.$row, '');
                 $this->setCellValue('GJ'.$row, '');
                 $this->setCellValue('GK'.$row, '');
                 $this->setCellValue('GL'.$row, '');
                 $this->setCellValue('GM'.$row, '');
                 $this->setCellValue('GN'.$row, '');
                 $this->setCellValue('GO'.$row, '');
                 $this->setCellValue('GP'.$row, '');
                 $this->setCellValue('GQ'.$row, '');
                 $this->setCellValue('GR'.$row, '');
                 $this->setCellValue('GS'.$row, '');
                 $this->setCellValue('GT'.$row, '');
                 $this->setCellValue('GU'.$row, '');
                 $this->setCellValue('GV'.$row, '');
                 $this->setCellValue('GW'.$row, '');
                 $this->setCellValue('GX'.$row, '');
                 $this->setCellValue('GY'.$row, '');
                 $this->setCellValue('GZ'.$row, '');

                 $this->setCellValue('HA'.$row, '');
                 $this->setCellValue('HB'.$row, '');
                 $this->setCellValue('HC'.$row, '');
                 $this->setCellValue('HD'.$row, '');
                 $this->setCellValue('HE'.$row, '');
                 $this->setCellValue('HF'.$row, '');
                 $this->setCellValue('HG'.$row, '');
                 $this->setCellValue('HH'.$row, '');
                 $this->setCellValue('HI'.$row, '');
                 $this->setCellValue('HJ'.$row, '');
                 $this->setCellValue('HK'.$row, '');
                 $this->setCellValue('HI'.$row, '');
                 $this->setCellValue('HJ'.$row, '');
                 $this->setCellValue('HK'.$row, '');
                 $this->setCellValue('HL'.$row, '');
                 $this->setCellValue('HM'.$row, '');
                 $this->setCellValue('HN'.$row, '');
                 $this->setCellValue('HO'.$row, '');
                 $this->setCellValue('HP'.$row, '');
                 $this->setCellValue('HQ'.$row, '');
                 $this->setCellValue('HR'.$row, '');
                 $this->setCellValue('HS'.$row, '');
                 $this->setCellValue('HT'.$row, '');
                 $this->setCellValue('HU'.$row, '');
                 $this->setCellValue('HV'.$row, '');
                 $this->setCellValue('HW'.$row, '');
                 $this->setCellValue('HX'.$row, '');
                 $this->setCellValue('HY'.$row, '');
                 $this->setCellValue('HZ'.$row, '');

                 $this->setCellValue('IA'.$row, '');
                 $this->setCellValue('IB'.$row, '');
                 $this->setCellValue('IC'.$row, '');
                 $this->setCellValue('ID'.$row, '');

            }
            $row++;
        } 
        $this->currentRow = $row; 
    }
    private function setExcelHeaderRow()
    {
        $row = $this->currentRow;
        $this->setColumnValueAndWidth('A',$row, "Waybill Typ"); 
        $this->setColumnValueAndWidth('B',$row, "AWB Prefix"); 
        $this->setColumnValueAndWidth('C',$row, "AWB Number"); 
        $this->setColumnValueAndWidth('D',$row, "HAWB Number"); 
        $this->setColumnValueAndWidth('E',$row, "Package Track No");
        $this->setColumnValueAndWidth('F',$row, "Airport Of Origin");
        $this->setColumnValueAndWidth('G',$row, "Permit to Proceed Destination Airport");
        $this->setColumnValueAndWidth('H',$row, "Date of Arrival at the Permit to Proceed Destination Airport");
        $this->setColumnValueAndWidth('I',$row, "Airport Of Arrival");
        $this->setColumnValueAndWidth('J',$row, "Cargo Terminal Operator");
        $this->setColumnValueAndWidth('K',$row, "Importing Carrier Air Carrier Code");
        $this->setColumnValueAndWidth('L',$row, "Flight Number");
        $this->setColumnValueAndWidth('M',$row, "Scheduled Date Of Arrival");
        $this->setColumnValueAndWidth('N',$row, "Boarded Quantity Identifier");
        $this->setColumnValueAndWidth('O',$row, "Boarded Pieces");
        $this->setColumnValueAndWidth('P',$row, "Boarded Weight");
        $this->setColumnValueAndWidth('Q',$row, "Boarded Weight Code");
        $this->setColumnValueAndWidth('R',$row, "Part Arrival Reference");
        $this->setColumnValueAndWidth('S',$row, "Food Facility Reg Exemption");
        $this->setColumnValueAndWidth('T',$row, "Manufacturer Registration Number");
        $this->setColumnValueAndWidth('U',$row, "Shipper Name");
        $this->setColumnValueAndWidth('V',$row, "Shipper Street Address");
        $this->setColumnValueAndWidth('W',$row, "Shipper City");
        $this->setColumnValueAndWidth('X',$row, "Shipper State or Province");
        $this->setColumnValueAndWidth('Y',$row, "Shipper Postal Code");
        $this->setColumnValueAndWidth('Z',$row, "Shipper Country");
        
        $this->setColumnValueAndWidth('AA',$row,"Shipper Telephone Number");
        $this->setColumnValueAndWidth('AB',$row, "Consignee Name");
        $this->setColumnValueAndWidth('AC',$row, "Consignee Identifier Code");
        $this->setColumnValueAndWidth('AD',$row,"Consignee Tax ID");
        $this->setColumnValueAndWidth('AE',$row,"Consignee Street Address");
        $this->setColumnValueAndWidth('AF',$row,"Consignee City");
        $this->setColumnValueAndWidth('AG',$row,"Consignee State or Province");
        $this->setColumnValueAndWidth('AH',$row,"Consignee Postal Code");
        $this->setColumnValueAndWidth('AI',$row,"Consignee Country");
        $this->setColumnValueAndWidth('AJ',$row,"Cargo Piece Count");
        $this->setColumnValueAndWidth('AK',$row,"Cargo Weight");
        $this->setColumnValueAndWidth('AL',$row,"Cargo Weight UOM");
        $this->setColumnValueAndWidth('AM',$row,"Consignee Telephone Number");
        $this->setColumnValueAndWidth('AN',$row,"Cargo Description");
        $this->setColumnValueAndWidth('AO',$row,"Marks and Numbers");
        $this->setColumnValueAndWidth('AP',$row,"Air AMS Participant Code");
        $this->setColumnValueAndWidth('AQ',$row,"Inbond Destination Airport");
        $this->setColumnValueAndWidth('AR',$row,"Inbond Destination Type");
        $this->setColumnValueAndWidth('AS',$row,"Bonded Carrier ID");
        $this->setColumnValueAndWidth('AT',$row,"Onward Carrier");
        $this->setColumnValueAndWidth('AU',$row,"Transfer FIRMS");
        $this->setColumnValueAndWidth('AV',$row,"Inbond Control Number");
        $this->setColumnValueAndWidth('AW',$row,"FDA Indicator");
        $this->setColumnValueAndWidth('AX',$row,"ACAS Filing");
        $this->setColumnValueAndWidth('AY',$row,"IncludeType86");
        $this->setColumnValueAndWidth('AZ',$row,"Entry Type");

        $this->setColumnValueAndWidth('BA',$row,"T86 Date of Arrival");
        $this->setColumnValueAndWidth('BB',$row,"IOR Type");
        $this->setColumnValueAndWidth('BC',$row,"IOR Number");
        $this->setColumnValueAndWidth('BD',$row,"Mode of Transport");
        $this->setColumnValueAndWidth('BE',$row,"Bond Type");
        $this->setColumnValueAndWidth('BF',$row,"Cargo Location FIRMS");
        $this->setColumnValueAndWidth('BG',$row,"Surety Code");
        $this->setColumnValueAndWidth('BH',$row,"Bond Amount");
        $this->setColumnValueAndWidth('BI',$row,"Express Consigment Shipment");
        $this->setColumnValueAndWidth('BJ',$row,"Known Importer");
        $this->setColumnValueAndWidth('BK',$row,"Perishable Goods");
        $this->setColumnValueAndWidth('BL',$row,"Additional Reference Code A");
        $this->setColumnValueAndWidth('BM',$row,"Additional Reference Number A");
        $this->setColumnValueAndWidth('BN',$row,"Additional Reference Code B");
        $this->setColumnValueAndWidth('BO',$row,"Additional Reference Number B");
        $this->setColumnValueAndWidth('BP',$row,"Port of Entry");
        $this->setColumnValueAndWidth('BQ',$row,"Equipment Number");
        $this->setColumnValueAndWidth('BR',$row,"HTS Number 1");
        $this->setColumnValueAndWidth('BS',$row,"Description 1");
        $this->setColumnValueAndWidth('BT',$row,"Line Item Value 1");
        $this->setColumnValueAndWidth('BU',$row,"Country of Origin 1");
        $this->setColumnValueAndWidth('BV',$row,"PGA FDA Disclaimer 1");
        $this->setColumnValueAndWidth('BW',$row,"Prior Notice Confirmation Number 1");
        $this->setColumnValueAndWidth('BX',$row,"PGA Product ID 1");
        $this->setColumnValueAndWidth('BY',$row,"PGA Packaging Qty 1 - 1");
        $this->setColumnValueAndWidth('BZ',$row,"PGA Packaging UOM 1 - 1");

        $this->setColumnValueAndWidth('CA',$row,"PGA Packaging Qty 1 - 2");
        $this->setColumnValueAndWidth('CB',$row,"PGA Packaging UOM 1 - 2");
        $this->setColumnValueAndWidth('CC',$row,"PGA Packaging Qty 1 - 3");
        $this->setColumnValueAndWidth('CD',$row,"PGA Packaging UOM 1 - 3");
        $this->setColumnValueAndWidth('CE',$row,"PGA Packaging Qty 1 - 4");
        $this->setColumnValueAndWidth('CF',$row,"PGA Packaging UOM 1 - 4");
        $this->setColumnValueAndWidth('CG',$row,"PGA Packaging QTY 1 - 5");
        $this->setColumnValueAndWidth('CH',$row,"PGA Packaging UOM 1 - 5");
        $this->setColumnValueAndWidth('CI',$row,"PGA Packaging QTY 1 - 6");
        $this->setColumnValueAndWidth('CJ',$row,"PGA Packaging UOM 1 - 6");
        $this->setColumnValueAndWidth('CK',$row,"Gross Net Quantity 1");
        $this->setColumnValueAndWidth('CL',$row,"Gross Net UOM 1");
        $this->setColumnValueAndWidth('CM',$row,"HTS Number 2");
        $this->setColumnValueAndWidth('CN',$row,"Description 2");
        $this->setColumnValueAndWidth('CO',$row,"Line Item Value 2");
        $this->setColumnValueAndWidth('CP',$row,"Country of Origin 2");
        $this->setColumnValueAndWidth('CQ',$row,"PGA FDA Disclaimer 2");
        $this->setColumnValueAndWidth('CR',$row,"PGA Product ID 2");
        $this->setColumnValueAndWidth('CS',$row,"Prior Notice Confirmation Number 2");
        $this->setColumnValueAndWidth('CT',$row,"PGA Packaging Qty 2 - 1");
        $this->setColumnValueAndWidth('CU',$row,"PGA Packaging UOM 2 - 1");
        $this->setColumnValueAndWidth('CV',$row,"PGA Packaging Qty 2 - 2");
        $this->setColumnValueAndWidth('CW',$row,"PGA Packaging UOM 2 - 2");
        $this->setColumnValueAndWidth('CX',$row,"PGA Packaging Qty 2 - 3");
        $this->setColumnValueAndWidth('CY',$row,"PGA Packaging UOM 2 - 3");
        $this->setColumnValueAndWidth('CZ',$row,"PGA Packaging Qty 2 - 4");
        $this->setColumnValueAndWidth('DA',$row,"PGA Packaging UOM 2 - 4");
        $this->setColumnValueAndWidth('DB',$row,"PGA Packaging Qty 2 - 5");
        $this->setColumnValueAndWidth('DC',$row,"PGA Packaging UOM 2 - 5");
        $this->setColumnValueAndWidth('DD',$row,"PGA Packaging Qty 2 - 6");
        $this->setColumnValueAndWidth('DE',$row,"PGA Packaging UOM 2 - 6");
        $this->setColumnValueAndWidth('DF',$row,"Gross Net Quantity 2");
        $this->setColumnValueAndWidth('DG',$row,"Gross Net UOM 2");


        $this->setColumnValueAndWidth('DH',$row,"HTS Number 3");
        $this->setColumnValueAndWidth('DI',$row,"Description 3");
        $this->setColumnValueAndWidth('DJ',$row,"Line Item Value 3");
        $this->setColumnValueAndWidth('DK',$row,"Country of Origin 3");
        $this->setColumnValueAndWidth('DL',$row,"PGA FDA Disclaimer 3");
        $this->setColumnValueAndWidth('DM',$row,"PGA Product ID 3");
        $this->setColumnValueAndWidth('DN',$row,"Prior Notice Confirmation Number 3");
        $this->setColumnValueAndWidth('DO',$row,"PGA Packaging Qty 3 - 1");
        $this->setColumnValueAndWidth('DP',$row,"PGA Packaging UOM 3 - 1");
        $this->setColumnValueAndWidth('DQ',$row,"PGA Packaging Qty 3 - 2");
        $this->setColumnValueAndWidth('DR',$row,"PGA Packaging UOM 3 - 2");
        $this->setColumnValueAndWidth('DS',$row,"PGA Packaging Qty 3 - 3");
        $this->setColumnValueAndWidth('DT',$row,"PGA Packaging UOM 3 - 3");
        $this->setColumnValueAndWidth('DU',$row,"PGA Packaging Qty 3 - 4");
        $this->setColumnValueAndWidth('DV',$row,"PGA Packaging UOM 3 - 4");
        $this->setColumnValueAndWidth('DW',$row,"PGA Packaging Qty 3 - 5");
        $this->setColumnValueAndWidth('DX',$row,"PGA Packaging UOM 3 - 5");
        $this->setColumnValueAndWidth('DY',$row,"PGA Packaging Qty 3 - 6");
        $this->setColumnValueAndWidth('DZ',$row,"PGA Packaging UOM 3 - 6");

        $this->setColumnValueAndWidth('EA',$row,"Gross Net Quantity 3");
        $this->setColumnValueAndWidth('EB',$row,"Gross Net UOM 3");
        $this->setColumnValueAndWidth('EC',$row,"HTS Number 4");
        $this->setColumnValueAndWidth('ED',$row,"Description 4");
        $this->setColumnValueAndWidth('EE',$row,"Line Item Value 4");
        $this->setColumnValueAndWidth('EF',$row,"Country of Origin 4");
        $this->setColumnValueAndWidth('EG',$row,"PGA FDA Disclaimer 4");
        $this->setColumnValueAndWidth('EH',$row,"PGA Product ID 4");
        $this->setColumnValueAndWidth('EI',$row,"Prior Notice Confirmation Number 4");
        $this->setColumnValueAndWidth('DJ',$row,"PGA Packaging Qty 4 - 1");
        $this->setColumnValueAndWidth('EK',$row,"PGA Packaging UOM 4 - 1");
        $this->setColumnValueAndWidth('EL',$row,"PGA Packaging Qty 4 - 2");
        $this->setColumnValueAndWidth('EM',$row,"PGA Packaging UOM 4 - 2");
        $this->setColumnValueAndWidth('EN',$row,"PGA Packaging Qty 4 - 3");
        $this->setColumnValueAndWidth('EO',$row,"PGA Packaging UOM 4 - 3");
        $this->setColumnValueAndWidth('EP',$row,"PGA Packaging Qty 4 - 4");
        $this->setColumnValueAndWidth('EQ',$row,"PGA Packaging UOM 4 - 4");
        $this->setColumnValueAndWidth('ER',$row,"PGA Packaging Qty 4 - 5");
        $this->setColumnValueAndWidth('ES',$row,"PGA Packaging UOM 4 - 5");
        $this->setColumnValueAndWidth('ET',$row,"PGA Packaging Qty 4 - 6");
        $this->setColumnValueAndWidth('EU',$row,"PGA Packaging UOM 4 - 6");
        $this->setColumnValueAndWidth('EV',$row,"Gross Net Quantity 4");
        $this->setColumnValueAndWidth('EW',$row,"Gross Net UOM 4");
        $this->setColumnValueAndWidth('EX',$row,"HTS Number 5");
        $this->setColumnValueAndWidth('EY',$row,"Description 5");
        $this->setColumnValueAndWidth('EZ',$row,"Line Item Value 5");

        $this->setColumnValueAndWidth('FA',$row,"Country of Origin 5");
        $this->setColumnValueAndWidth('FB',$row,"PGA FDA Disclaimer 5");
        $this->setColumnValueAndWidth('FC',$row,"PGA Product ID 5");
        $this->setColumnValueAndWidth('FD',$row,"Prior Notice Confirmation Number 5");
        $this->setColumnValueAndWidth('FE',$row,"PGA Packaging Qty 5 - 1");
        $this->setColumnValueAndWidth('FF',$row,"PGA Packaging UOM 5 - 1");
        $this->setColumnValueAndWidth('FG',$row,"PGA Packaging Qty 5 - 2");
        $this->setColumnValueAndWidth('FH',$row,"PGA Packaging UOM 5 - 2");
        $this->setColumnValueAndWidth('FI',$row,"PGA Packaging Qty 5 - 3");
        $this->setColumnValueAndWidth('FJ',$row,"PGA Packaging UOM 5 - 3");
        $this->setColumnValueAndWidth('FK',$row,"PGA Packaging Qty 5 - 4");
        $this->setColumnValueAndWidth('FL',$row,"PGA Packaging UOM 5 - 4");
        $this->setColumnValueAndWidth('FM',$row,"PGA Packaging Qty 5 - 5");
        $this->setColumnValueAndWidth('FN',$row,"PGA Packaging UOM 5 - 5");
        $this->setColumnValueAndWidth('FO',$row,"PGA Packaging Qty 5 - 6");
        $this->setColumnValueAndWidth('FP',$row,"PGA Packaging UOM 5 - 6");
        $this->setColumnValueAndWidth('FQ',$row,"Gross Net Quantity 5");
        $this->setColumnValueAndWidth('FR',$row,"Gross Net UOM 5");
        $this->setColumnValueAndWidth('FS',$row,"HTS Number 6");
        $this->setColumnValueAndWidth('FT',$row,"Description 6");
        $this->setColumnValueAndWidth('FU',$row,"Line Item Value 6");
        $this->setColumnValueAndWidth('FV',$row,"Country of Origin 6");
        $this->setColumnValueAndWidth('FW',$row,"PGA FDA Disclaimer 6");
        $this->setColumnValueAndWidth('FX',$row,"PGA Product ID 6");
        $this->setColumnValueAndWidth('FY',$row,"Prior Notice Confirmation Number 6");
        $this->setColumnValueAndWidth('FZ',$row,"PGA Packaging Qty 6 - 1");

        $this->setColumnValueAndWidth('GA',$row,"PGA Packaging UOM 6 - 1");
        $this->setColumnValueAndWidth('GB',$row,"PGA Packaging Qty 6 - 2");
        $this->setColumnValueAndWidth('GC',$row,"PGA Packaging UOM 6 - 2");
        $this->setColumnValueAndWidth('GD',$row,"PGA Packaging Qty 6 - 3");
        $this->setColumnValueAndWidth('GE',$row,"PGA Packaging UOM 6 - 3");
        $this->setColumnValueAndWidth('GF',$row,"PGA Packaging Qty 6 - 4");
        $this->setColumnValueAndWidth('GG',$row,"PGA Packaging UOM 6 - 4");
        $this->setColumnValueAndWidth('GH',$row,"PGA Packaging Qty 6 - 5");
        $this->setColumnValueAndWidth('GI',$row,"PGA Packaging UOM 6 - 5");
        $this->setColumnValueAndWidth('GJ',$row,"PGA Packaging Qty 6 - 6");
        $this->setColumnValueAndWidth('GK',$row,"PGA Packaging UOM 6 - 6");
        $this->setColumnValueAndWidth('GL',$row,"Gross Net Quantity 6");
        $this->setColumnValueAndWidth('GM',$row,"Gross Net UOM 6");
        $this->setColumnValueAndWidth('GN',$row,"HTS Number 7");
        $this->setColumnValueAndWidth('GO',$row,"Description 7");
        $this->setColumnValueAndWidth('GP',$row,"Line Item Value 7");
        $this->setColumnValueAndWidth('GQ',$row,"Country of Origin 7");
        $this->setColumnValueAndWidth('GR',$row,"PGA FDA Disclaimer 7");
        $this->setColumnValueAndWidth('GS',$row,"PGA Product ID 7");
        $this->setColumnValueAndWidth('GT',$row,"Prior Notice Confirmation Number 7");
        $this->setColumnValueAndWidth('GU',$row,"PGA Packaging Qty 7 - 1");
        $this->setColumnValueAndWidth('GV',$row,"PGA Packaging UOM 7 - 1");
        $this->setColumnValueAndWidth('GW',$row,"PGA Packaging Qty 7 - 2");
        $this->setColumnValueAndWidth('GX',$row,"PGA Packaging UOM 7 - 2");
        $this->setColumnValueAndWidth('GY',$row,"PGA Packaging Qty 7 - 3");
        $this->setColumnValueAndWidth('GZ',$row,"PGA Packaging UOM 7 - 3");
        
        $this->setColumnValueAndWidth('HA',$row,"PGA Packaging Qty 7 - 4");
        $this->setColumnValueAndWidth('HB',$row,"PGA Packaging UOM 7 - 4");
        $this->setColumnValueAndWidth('HC',$row,"PGA Packaging Qty 7 - 5");
        $this->setColumnValueAndWidth('HD',$row,"PGA Packaging UOM 7 - 5");
        $this->setColumnValueAndWidth('HE',$row,"PGA Packaging Qty 7 - 6");
        $this->setColumnValueAndWidth('HF',$row,"PGA Packaging UOM 7 - 6");
        $this->setColumnValueAndWidth('HG',$row,"Gross Net Quantity 7");
        $this->setColumnValueAndWidth('HH',$row,"Gross Net UOM 7");
        $this->setColumnValueAndWidth('HI',$row,"HTS Number 8");
        $this->setColumnValueAndWidth('HJ',$row,"Description 8");
        $this->setColumnValueAndWidth('HK',$row,"Line Item Value 8");
        $this->setColumnValueAndWidth('HL',$row,"Country of Origin 8");
        $this->setColumnValueAndWidth('HM',$row,"PGA FDA Disclaimer 8");
        $this->setColumnValueAndWidth('HN',$row,"PGA Product ID 8");
        $this->setColumnValueAndWidth('HO',$row,"Prior Notice Confirmation Number 8");
        $this->setColumnValueAndWidth('HP',$row,"PGA Packaging Qty 8- 1");
        $this->setColumnValueAndWidth('HQ',$row,"PGA Packaging UOM 8 - 1");
        $this->setColumnValueAndWidth('HR',$row,"PGA Packaging Qty 8 - 2");
        $this->setColumnValueAndWidth('HS',$row,"PGA Packaging UOM 8 - 2");
        $this->setColumnValueAndWidth('HT',$row,"PGA Packaging Qty 8 - 3");
        $this->setColumnValueAndWidth('HU',$row,"PGA Packaging UOM 8 - 3");
        $this->setColumnValueAndWidth('HV',$row,"PGA Packaging Qty 8 - 4");
        $this->setColumnValueAndWidth('HW',$row,"PGA Packaging UOM 8 - 4");
        $this->setColumnValueAndWidth('HX',$row,"PGA Packaging Qty 8 - 5");
        $this->setColumnValueAndWidth('HY',$row,"PGA Packaging UOM 8 - 5");
        $this->setColumnValueAndWidth('HZ',$row,"PGA Packaging Qty 8 - 6");
        
        $this->setColumnValueAndWidth('IA',$row,"PGA Packaging UOM 8 - 6");
        $this->setColumnValueAndWidth('IB',$row,"Gross Net Quantity 8");
        $this->setColumnValueAndWidth('IC',$row,"Gross Net UOM 8");
        $this->setColumnValueAndWidth('ID',$row,"UOM 8");
        
        // $this->setBackgroundColor('A',$this->currentRow.':ID',$this->currentRow, "2b5cab");
        // $this->setColor('A',$this->currentRow.':ID',$this->currentRow, "FFFFFF");
        $this->currentRow++;    
    }
    public function setColumnValueAndWidth($column,$row,$value,$width=30)
    {
        $this->setColumnWidth($column, $width);
         $this->setCellValue($column.$row, $value);  
    }
}
